---
title: "R Code Documentation"
author: "Saul-42"
format: pdf
editor: visual
---

## NOTES

This file will index and track all changes and modifications made to the actual code scripts for the entire duration of the PhD. project.

**IMPORTANT NOTE:** As at present we are still in the transition between `move` and `move2`, all the Scripts will have code that works with the `move` package or the updated `move2` package. It might be necessary to convert between the two object types. The idea is to use either one in the workflow as `move2` gets brought to full functionality.

Folder Structure for the Workspace

-   Data_Raw folder

    For movement data downloaded from Movebank. SOP is to delete any older files when new ones are brought in. This is currently only necessary for the few (5 as of Dec.2023) birds still transmitting new data.

-   Data_Cleaned

    For movement data that has been cleaned of duplicates, multi-locations and had its dates checked. As both `move` and `move2` packages are being used to analyse the data, ultimately two files for each Vulture will be created, with a specific naming convention for the outputs of each cleaning algorithm. `move`-cleaned data will be "Mv1.Cln.Vult\<number\>data.Rdata; and `move2`-cleaned data will be"Mv2.ClnLocs.Vult\<number\>.Rdata".

-   Data_Processed

    For movement datasets after they have undergone transformations.

-   Scripts

    Dedicated for Script `.R` files

-   Visualizations

    For the outputs of visual analysis, like graphs, plots, maps, etc.

### Version 1.0 of code and script organization

The initial layout is a series of `.R` scripts with numbers (format `00. ; 01. ;...`) as an ascending indexing system. Each script is dedicated to a particular task of the workflow dealing with movement data, like "Clean data" and "Calculate Home Ranges". Branches and/or additional steps in the workflow that entail their own separate set of instructions can also be included (format `01A. ; 01B. ; 02A. ;...`) .

Each script will have a short description of its intended function, followed by a section with commands to load all the necessary R packages used in that specific code. Then it will have sections dedicated to each individual step of the particular task, using the format "\# <Step Name> -------...". The number of hash in each Section name follows standard Markdown notation for headings in descending order of importance.

### Version 2.0 of code and script organization

The script organization system will be changed due to flexibility issues. The neat separation in ascending numbers doesn't take into account branches or alternative paths, and makes it cumbersome to place certain codes that must be applied to just specific situations.

The .R scripts will be named according to a letter

## Notes on Script 01: CLEAN DATA

### `Move` (Old) Workflow:

1.  The movement data has to be downloaded from the Movebank online repository in `.csv` format, and then imported to the R environment using the function `read.csv()`, as the size of the datasets makes them difficult to wield using the available internet speed.

2.  In the Animove Script (ref: Lesson_2_2022) there is the option of using the `move()` function for directly importing the `.csv`, but when using it to import the T.Vulture data, an error appears:

    (`Error in validityMethod(as(object, superClass)) : The dataset includes double timestamps first one:2021-01-13 23:00:08)`)

    `(S42 NOTE)(#Opinion)(27/10/2023)` This is likely due to multi-location entries, therefore making it necessary to pre-process the dataset first. Check time stamps and eliminate duplicates and multi-locations before converting the dataset to the Move class format.

3.  In the `as.POSIXct()` function, the argument `format = "%F %T"` uses these values as "%F" is equivalent to %Y-%m-%d and "%T" is equivalent to %H:%M:%S.

### `Move2` (New) Workflow:

1.  `(S42 NOTE)` The option of running the Old Workflow using the `move` package and the convert the resulting object to the `move2` type is available in the Script.

2.  The presence of missing values in the dataset can now be due to the inclusion of non-location data from other sensors (ACC, MAG, etc.) in the same `move2` object. However, if the analysis to be carried over only encompasses the use of GPS data, then is recommendable to eliminate them to save memory space.

    This means that we might be producing two different kind of `move2` objects at the end of the `Script 01: CLEAN DATA`, one tight dataset containing strictly the data from the GPS sensor, and the other containing data from all the other sensors besides.

3.  The new algorithm produces a different result when outputting a clean dataset without duplicates or incomplete registries. The raw data of Vulture "Cuba-7198" (that has 1.511.956 observations when downloaded from Movebank) produces:

    -   The old script (uses package `move`) takes the raw data and leaves it with 302.309 elements after cleaning it.

    -   The new script (uses package `move2`) outputs 302.331 elements after the clean process is over, meaning that 21 records don't get deleted by the new algorithm.

        -   `IDEA`: Compare the two Cleaned datasets to look for the differing locations. It might be necessary to implement this across multiple individuals to pinpoint the possible causes of the differences in outputs between the two algorithms.

4.  The new algorithm also is inconsistent with the amount of variables that leaves in the movement data when the `.csv` file is cleaned of duplicates and missing values. Some Vulture's data has 41 variables, and others has 43, for example.

## Notes on Script 02: EXPLORE AND VISUALIZE DATA

### `Move` (Old) Workflow:

1.  When the table with the temporal distribution of records across time of the day and months of the year is printed, there are some months with `NA` values at some hours of the day. This might or might not be a problem for future analysis. Some times maybe should be removed from the dataset to make reliable statistical comparisons.
2.  `(S42 NOTE)` There is a section on the Script of the Lesson ¨Initial Exploration of Movement Data¨ of Animove 2022 related to Missed Fixes (the last section), where they deal with them. The problem is that different tag models record empty fixes as NA values in `Lon` and `Lat`, and others just don't record anything and jump the fix. I have doubts regarding if the Vulture data has missed fixes, but the most likely is that the empty values were eliminated during the Cleaning process.

### `Move2` (New) Workflow:

1.  `(S42 NOTE)` None of the functions in the Animove Script (ref: Lesson_3_2023) for plotting the movement data on a map works. There are error messages with both the `rnaturalearth` package use and the `ggmap::get_map` function. The later is likely due to connection permit issues in Cuba (last tried in 2/2/2024, using mobile data + hotspot to connect to the internet), [`<TO CHECK>`]{.underline} if the function works outside of Cuba.

2.  Function `mapview()` of the same-name package doesn't work with `move2` objects, but it does it with objects of class `sf`.

    -   Therefore, it's necessary remove class "move2" from object and let it with `sf`.

## Notes on Script 03: ANALYZE TRAJECTORIES

### `Move2` (New) Workflow:

1.  `(S42 NOTE)` Consider if it would be necessary to use a dynamic Brownian Bridge Movement Model to analyze the variance of movement in the Turkey Vultures.

### **`UNFINISHED...`**

## Notes on Script 04: ANALYZE AREAS

### `Move` (Old) Workflow:
